spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-wz9184d1t788ka987mo.mysql.rds.aliyuncs.com:3306/video_db?autoReconnect=true&useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC
    username: video
    password: 1qaz@WSX
  devtools:
    restart:
      enabled: true     #开启热部署
  thymeleaf:
    cache: false        #页面修改后不重启
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html

#日志
logging:
  level:
    root: info
    org:
      springframework:
        web: warn
      apache:
        tomcat: warn
    com:
      jushu:
        video:
          mapper: debug

server:
  port: 9700
